steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/getmp3-ui:latest', '-t', 'gcr.io/$PROJECT_ID/getmp3-ui:$TAG_NAME', '.']
images:
- 'gcr.io/$PROJECT_ID/getmp3-ui:$TAG_NAME'
- 'gcr.io/$PROJECT_ID/getmp3-ui:latest'
